tpokorasite/payroll/urls.py
#!/usr/bin/env python
from django.conf.urls import patterns, url
from payroll import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^(?P<param>\D*)/$', views.mainSite, name='mainSite'),
    url(r'^customers/batch$', views.customerBatch, name='customerBatch'),
    url(r'^suppliers/batch$', views.supplierBatch, name='suppliersBatch'),
)

tpokorasite/tpokorasite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tpokorasite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^payroll/', include('payroll.urls', namespace='payroll')),
    url(r'^admin/', include(admin.site.urls)),
)

tpokorasite/payroll/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    number = models.CharField(max_length=10, )
    name = models.CharField(max_length=255)
    date = models.DateTimeField('date registered')
    

class Supplier(models.Model):
    number = models.CharField(max_length=10)
    name = models.CharField(max_length=255)
    date = models.DateTimeField('date registered')
    
    
class CustomerBatch(models.Model):
    customer = models.ForeignKey(Customer)
    description = models.CharField(max_length=255)
    date = models.DateTimeField('date registered')
    price = models.FloatField()


class SupplierBatch(models.Model):
    supplier = models.ForeignKey(Supplier)
    description = models.CharField(max_length=255)
    date = models.DateTimeField('date registered')
    price = models.FloatField()
    

tpokorasite/payroll/views.py
from django.shortcuts import render
from django.utils import timezone
from payroll.models import Customer, Supplier, CustomerBatch, SupplierBatch
from django.http import HttpResponseRedirect

# Create your views here.
# welcome view
def home(request):
    menuLinks = ('customers', 'suppliers', 'bank')
    return render(request, 'payroll/index.html', {'menuLinks' : menuLinks,})

# mainsite view
def mainSite(request, param):
    menuLinks = ('customers', 'suppliers')
    customers = Customer.objects.all()
    suppliers = Supplier.objects.all()
    if (param == 'newCustomer'):
        number = request.POST['customerNumber']
        name = request.POST['customerName']
        addNewCustomer(name, number)
        customers = Customer.objects.all()
        return HttpResponseRedirect('customers')
    if (param == 'newSupplier'):
        number = request.POST['supplierNumber']
        name = request.POST['supplierName']
        addNewSupplier(name, number)
        suppliers = Supplier.objects.all()
        return HttpResponseRedirect('suppliers')
    
    return render(request, 'payroll/index.html', {'menuLinks' : menuLinks,
                                                  'customers' : customers,
                                                  'suppliers' : suppliers,
                                                  'opt' : param})


def addNewCustomer(name, number):
    customer = Customer(number=number, name=name, date=timezone.now())
    print 'Acction:'
    print 'Adding customer to database:'
    print 'customer number: ' + customer.number
    print 'customer name: ' + customer.name
    print 'register date: ' + str(customer.date)
    customer.save()
    
def addNewSupplier(name, number):
    supplier = Supplier(number=number, name=name, date=timezone.now())
    print 'Acction:'
    print 'Adding supplier to database:'
    print 'supplier number: ' + supplier.number
    print 'supplier name: ' + supplier.name
    print 'register date: ' + str(supplier.date)
    supplier.save()
    

# batches view
def customerBatch(request):
    menuLinks = ('customers', 'suppliers')
    customers = Customer.objects.all()
    customersBatch = CustomerBatch.objects.all()
    return render(request, 'payroll/batch.html', { 'menuLinks' : menuLinks,
                                                   'customers' : customers,
                                                   'customersBatch' : customersBatch,
                                                   'opt' : 'customers'})


def supplierBatch(request):
    menuLinks = ('customers', 'suppliers')
    suppliers = Supplier.objects.all()
    suppliersBatch = SupplierBatch.objects.all()
    return render(request, 'payroll/batch.html', { 'menuLinks' : menuLinks,
                                                   'suppliers' : suppliers,
                                                   'suppliers' : suppliersBatch,
                                                   'opt' : 'suppliers', })

tpokorasite/payroll/templates/payroll/batch.html
<!DOCTYPE html>

<html>
<head>
    <title>Payroll manager</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'payroll/css/style.css' %}" />
    <script type="text/javascript" >
        document.addEventListener('DOMContentLoaded', function() {
            if ("{{ opt }}" == 'customers') {
                customersOpt.style.display = 'block';
                customersList.style.display = 'block';
                suppliersList.style.display = 'none';
            }
            if ("{{ opt }}" == 'suppliers') {
                suppliersOpt.style.display = 'block';
                suppliersList.style.display = 'block';
                customersList.style.display = 'none';
            }
        }, false);
    </script>
    <script src="{% static 'payroll/js/index.js' %}"></script>
</head>

<body>
<div id="wrapper">
    <h1 id="header" class="upper center">
        <a href="{% url 'payroll:home' %}" >Payroll</a>
    </h1>
    <div id="main">
        <div id="left-sidebar">
            <div id="customersOpt">
                <div class="leftMenu class="upper">
                    <div class="leftMenuTitle upper">Customers</div>
                    <a class="leftMenuLink upper" href="#"
                       onclick="showForm('newCustomer');">
                        New
                    </a>
                    <a class="leftMenuLink upper"
                       href="{% url 'payroll:customerBatch' %}">
                        Batch
                    </a>
                    <a class="leftMenuLink upper"
                       href="{% url 'payroll:mainSite' 'customers' %}">
                        List
                    </a>
                </div>
            </div>
            <div id="suppliersOpt">
                <div class="leftMenu">
                    <div class="leftMenuTitle upper">Supplires</div>
                    <a class="leftMenuLink upper" href="#"
                        onclick="showForm('newSupplier');">
                        New
                    </a>
                    <a class="leftMenuLink upper"
                       href="{% url 'payroll:suppliersBatch' %}">
                        Batch
                    </a>
                    <a class="leftMenuLink upper"
                       href="{% url 'payroll:mainSite' 'suppliers' %}">
                        List
                    </a>
                </div>
            </div>
            <div class="leftMenu">
                <div class="leftMenuTitle upper">Menu</div>
                {% for link in menuLinks %}
                <a class="leftMenuLink upper"
                   href="{% url 'payroll:mainSite' link %}">
                    {{ link }}
                </a>
                {% endfor %}
            </div>
        </div>
        <div id="details">
            <div id="customersList">
                <div id="newCustomer">
                    <form id="newUserForm" action="newCustomer" method="post">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <th colspan="2" class="upper">New user</th>
                            </tr>
                            <tr>
                                <td class="right">
                                    Number:
                                </td>
                                <td>
                                    <input type="text" name="customerNumber" />
                                </td> 
                            </tr>
                            <tr>
                                <td class="right">
                                    Name:
                                </td>
                                <td>
                                    <input type="text" name="customerName" />
                                    </td> 
                            </tr>
                            <tr>
                                <td colspan="2" class="center">
                                    <input type="submit" value="Register" />
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <div id="customerBatch">
                    {% if customersBatch %}
                        <table>
                            <tr>
                                <th class="center">Cust. No.</th>
                                <th class="center">Description</th>
                                <th class="center">Price</th>
                                <th class="center">Date</th>
                            </tr>
                            {% for batch in customersBatch %}
                            <tr>
                                <td class="center">{{ batch.customer.number }}</td>
                                <td class="center batchDesc">{{ batch.description }}</td>
                                <td class="center">{{ batch.price }}</td>
                                <td class="center regDate">{{ batch.date }}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <h2 class="center">No customer batch registered</h2>
                    {% endif %}
                </div>
            </div>
            <div id="suppliersList">
                <div id="newSupplier">
                    <form id="newSupplierForm" action="newSupplier" method="post">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <th colspan="2" class="upper">New supplier</th>
                            </tr>
                            <tr>
                                <td class="right">Number:</td>
                                <td><input type="text" name="supplierNumber" /></td> 
                            </tr>
                            <tr>
                                <td class="right">Name:</td>
                                <td><input type="text" name="supplierName" /></td> 
                            </tr>
                            <tr>
                                <td colspan="2" class="center">
                                    <input type="submit" value="Register" />
                                </td>
                            </tr>
                        </table> 
                    </form>
                </div>
                <div id="suppliersBatch">
                    
                    {% if suppliersBatch %}
                        <table>
                            <tr>
                                <th class="center">Supp. No.</th>
                                <th class="center">Description</th>
                                <th class="center">Price</th>
                                <th class="center">Date</th>
                            </tr>
                            {% for batch in suppliersBatch %}
                            <tr>
                                <td class="center">{{ batch.supplier.number }}</td>
                                <td class="center batchDesc">{{ batch.description }}</td>
                                <td class="center">{{ batch.price }}</td>
                                <td class="center regDate">{{ batch.date }}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <h2 class="center">No supplier batch registered</h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

tpokorasite/payroll/templates/payroll/index.html
<!DOCTYPE html>

<html>
<head>
    <title>Payroll manager</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'payroll/css/style.css' %}" />
    <script type="text/javascript" >
        document.addEventListener('DOMContentLoaded', function() {
            if ("{{ opt }}" == 'customers') {
                customersOpt.style.display = 'block';
                customersList.style.display = 'block';
                suppliersList.style.display = 'none';
                welcomeMsg.style.display = 'none';
            }
            if ("{{ opt }}" == 'suppliers') {
                suppliersOpt.style.display = 'block';
                suppliersList.style.display = 'block';
                customersList.style.display = 'none';
                welcomeMsg.style.display = 'none';
            }
        }, false);
    </script>
    <script src="{% static 'payroll/js/index.js' %}"></script>
</head>

<body>
<div id="wrapper">
    <h1 id="header" class="upper center">
        <a href="{% url 'payroll:home' %}" >Payroll</a>
    </h1>
    <div id="main">
        <div id="left-sidebar">
            <div id="customersOpt">
                <div class="leftMenu class="upper">
                    <div class="leftMenuTitle upper">Customers</div>
                    <a class="leftMenuLink upper" href="#"
                       onclick="showForm('newCustomer');">
                        New
                    </a>
                    <a class="leftMenuLink upper" href="#"
                       onclick="showForm('newOrder');">
                        Batch
                    </a>
                </div>
            </div>
            <div id="suppliersOpt">
                <div class="leftMenu">
                    <div class="leftMenuTitle upper">Supplires</div>
                    <a class="leftMenuLink upper" href="#"
                        onclick="showForm('newSupplier');">
                        New
                    </a>
                </div>
            </div>
            <div class="leftMenu">
                <div class="leftMenuTitle upper">Menu</div>
                {% for link in menuLinks %}
                <a class="leftMenuLink upper"
                   href="{% url 'payroll:mainSite' link %}">
                    {{ link }}
                </a>
                {% endfor %}
            </div>
        </div>
        <div id="details">
            <div id="welcomeMsg">
                <h2 class="center upper">Welcome to payroll manager!</h2>
            </div>
            <div id="customersList">
                <div id="newCustomer">
                    <form id="newUserForm" action="newCustomer" method="post">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <th colspan="2" class="upper">New user</th>
                            </tr>
                            <tr>
                                <td class="right">
                                    Number:
                                </td>
                                <td>
                                    <input type="text" name="customerNumber" />
                                </td> 
                            </tr>
                            <tr>
                                <td class="right">
                                    Name:
                                </td>
                                <td>
                                    <input type="text" name="customerName" />
                                    </td> 
                            </tr>
                            <tr>
                                <td colspan="2" class="center">
                                    <input type="submit" value="Register" />
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                
                <h2 class="center upper">Customers list</h2>
                <table>
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Registered</th>
                    </tr>
                    {% for customer in customers %}
                    <tr>
                        <td class="center">{{ customer.number }}</td>
                        <td class="center compName">{{ customer.name }}</td>
                        <td class="center regDate">{{ customer.date }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div id="suppliersList">
                <div id="newSupplier">
                    <form id="newSupplierForm" action="newSupplier" method="post">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <th colspan="2" class="upper">New supplier</th>
                            </tr>
                            <tr>
                                <td class="right">Number:</td>
                                <td><input type="text" name="supplierNumber" /></td> 
                            </tr>
                            <tr>
                                <td class="right">Name:</td>
                                <td><input type="text" name="supplierName" /></td> 
                            </tr>
                            <tr>
                                <td colspan="2" class="center">
                                    <input type="submit" value="Register" />
                                </td>
                            </tr>
                        </table> 
                    </form>
                </div>
                <h2 class="center upper">Suppliers list</h2>
                <table>
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Registered</th>
                    </tr>
                    {% for supplier in suppliers %}
                    <tr>
                        <td class="center">{{ supplier.number }}</td>
                        <td class="center compName">{{ supplier.name }}</td>
                        <td class="center regDate">{{ supplier.date }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>